Feature: CEA608/708 Subtitles Compatibility
streaming-video-technology-alliance/common-media-library pull request #75
Opened 2024-02-27 15:24 UTC by hernanr99

## Description
We've implemented support for the CEA608/708 subtitles standard to our library, expanding its capabilities. In this update, alongside the feature implementation, we've initiated the integration with a basic set of tests. 

## Requirements Checklist
- [X] Unit Tests updated or fixed
- [ ] Docs/guides updated

2024-02-27 17:28 UTC, littlespex requested changes

2024-02-27 17:28 UTC, littlespex commented on lib/src/captions/cea608-708/utilities/utils.ts
> +export function extractCea608DataFromRange(raw: any, cea608Range: any) {
Add proper data types for these args.

2024-02-29 18:45 UTC, mpollingerQualabs submitted a review, later dismissed
LGTM

2024-03-01 12:29 UTC, avelad commented
One question, do you support the subtitles described in https://github.com/videojs/mux.js/pull/439 ?

2024-03-01 13:32 UTC, mpollingerQualabs commented
> One question, do you support the subtitles described in [videojs/mux.js#439](https://github.com/videojs/mux.js/pull/439) ?

Hey @avelad, do you have a playlists we could test with? Or should we try with the one on that PR?

2024-03-01 13:44 UTC, avelad commented
> > One question, do you support the subtitles described in [videojs/mux.js#439](https://github.com/videojs/mux.js/pull/439) ?
> 
> Hey @avelad, do you have a playlists we could test with? Or should we try with the one on [that PR](https://solutions.brightcove.com/wseymour/708-testing/playlist.m3u8)?

Yes, you can use:
Example Test Playlist: https://solutions.brightcove.com/wseymour/708-testing/playlist.m3u8

2024-03-01 14:36 UTC, mpollingerQualabs commented
> > > One question, do you support the subtitles described in [videojs/mux.js#439](https://github.com/videojs/mux.js/pull/439) ?
> > 
> > 
> > Hey @avelad, do you have a playlists we could test with? Or should we try with the one on [that PR](https://solutions.brightcove.com/wseymour/708-testing/playlist.m3u8)?
> 
> Yes, you can use: Example Test Playlist: https://solutions.brightcove.com/wseymour/708-testing/playlist.m3u8

We've tried with that one but it doesn't seem to have a subtitle playlist. Could you provide us another one? Or what specific type of subtitle should we test?

2024-03-05 18:15 UTC, fyoungqualabs approved these changes

2024-03-05 18:40 UTC, mpollingerQualabs approved these changes

2024-04-05 19:00 UTC, merged